ims/ims/urls.py
"""
Definition of urls for ims.
"""

from django.contrib import admin
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView, PasswordChangeView, PasswordChangeDoneView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static
from mfa.views import LoginView
from . import views
import re

urlpatterns = [
    path('mfa/', include('mfa.urls', namespace='mfa')),
    path('accounts/admin/', include('accounts.admin.urls')),
    path('accounts/password_change/', PasswordChangeView.as_view(), name='password_change'),
    path('accounts/password_change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('accounts/password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('accounts/', include('accounts.urls')),
    path('admin/login/', LoginView.as_view()),
    path('admin/', admin.site.urls),
    path('inventory/admin/', include('inventory.admin.urls')),
    path('inventory/', include('inventory.urls')),
    path('logs/', include('log.urls')),
    path('api/v1/accounts/', include('accounts.api.urls')),
    path('api/v1/inventory/', include('inventory.api.urls')),
    path('api/v1/log/', include('log.api.urls')),
    path('api-auth/', include('rest_framework.urls')),
    re_path(r'^$', views.root_view, name='redirect'),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

regex = re.compile(r'ims.addons.*')
addons = [i for i in settings.INSTALLED_APPS if regex.match(i)]

for module in addons:
    name = module.replace('ims.addons.','')
    for line in settings.INSTALLED_ADDONS:
        if line['name'].lower() == name:
            if line['enabled']:
                if 'api_url' in line:
                    urlpatterns.append(path(line['api_url'], include('{}.api.urls'.format(module))))
                if 'admin_url' in line:
                    urlpatterns.append(path(line['admin_url'], include('{}.admin.urls'.format(module))))
                if 'url' in line:
                    urlpatterns.append(path(line['url'], include('{}.urls'.format(module))))
                if 'other_urls' in line:
                    array = line['other_urls'].split('|')
                    if len(array)%2 == 0:
                        i=0
                        while i < len(array):
                            urlpatterns.append(path(array[i].split(':')[1], include(array[i+1].split(':')[1])))
                            i+=2

ims/inventory/admin/urls.py
from django.urls import re_path
from inventory.admin import views

app_name='inventory.admin'
urlpatterns = [
    re_path(r'^$', views.home, name='home'),
    re_path(r'^part/$', views.admin_part_view, name='admin_part_view'),
    re_path(r'^part/create/$', views.admin_part_create, name='admin_part_create'),
    re_path(r'^part/change/(?P<id>[\d]+)/$', views.admin_part_change, name='admin_part_change'),
    re_path(r'^part/delete/(?P<id>[\d]+)/$', views.ajax_part_delete, name='ajax_part_delete'),
    re_path(r'^assembly/$', views.admin_assembly_view, name='admin_assembly_view'),
    re_path(r'^assembly/create/$', views.admin_assembly_create, name='admin_assembly_create'),
    re_path(r'^assembly/change/(?P<id>[\d]+)/$', views.admin_assembly_change, name='admin_assembly_change'),
    re_path(r'^assembly/delete/(?P<id>[\d]+)/$', views.ajax_assembly_delete, name='ajax_assembly_delete'),
    re_path(r'^storage/$', views.admin_storage_view, name='admin_storage_view'),
    re_path(r'^storage/create/$', views.admin_storage_create, name='admin_storage_create'),
    re_path(r'^storage/change/(?P<id>[\d]+)/$', views.admin_storage_change, name='admin_storage_change'),
    re_path(r'^storage/delete/(?P<id>[\d]+)/$', views.ajax_storage_delete, name='ajax_storage_delete'),
    re_path(r'^alternatesku/$', views.admin_alternatesku_view, name='views.admin_alternatesku_view'),
    re_path(r'^alternatesku/create/$', views.admin_alternatesku_create, name='admin_alternatesku_create'),
    re_path(r'^alternatesku/delete/(?P<id>[\d]+)/$', views.ajax_alternatesku_delete, name='ajax_alternatesku_delete'),
    re_path(r'^partstorage/$', views.admin_partstorage_view, name='views.admin_partstorage_view'),
    re_path(r'^partstorage/create/$', views.admin_partstorage_create, name='views.admin_partstorage_create'),
    re_path(r'^partstorage/change/(?P<id>[\d]+)/$', views.admin_partstorage_change, name='views.admin_partstorage_change'),
    re_path(r'^partstorage/delete/(?P<id>[\d]+)/$', views.ajax_partstorage_delete, name='ajax_partstorage_delete'),
    re_path(r'^partalternatesku/$', views.admin_partalternatesku_view, name='admin_partalternatesku_view'),
    re_path(r'^partalternatesku/create/$', views.admin_partalternatesku_create, name='admin_partalternatesku_create'),
    re_path(r'^partalternatesku/delete/(?P<id>[\d]+)/$', views.ajax_partalternatesku_delete, name='ajax_partalternatesku_delete'),
    re_path(r'^kit/$', views.admin_kit_view, name='admin_kit_view'),
    re_path(r'^kit/create/$', views.admin_kit_create, name='admin_kit_create'),
    re_path(r'^kit/change/(?P<id>[\d]+)/$', views.admin_kit_change, name='admin_kit_change'),
    re_path(r'^kit/delete/(?P<id>[\d]+)/$', views.ajax_kit_delete, name='ajax_kit_delete'),
    re_path(r'^kitpartstorage/$', views.admin_kitpartstorage_view, name='admin_kitpartstorage_view'),
    re_path(r'^kitpartstorage/create/$', views.admin_kitpartstorage_create, name='admin_kitpartstorage_create'),
    re_path(r'^kitpartstorage/change/(?P<id>[\d]+)/$', views.admin_kitpartstorage_change, name='admin_kitpartstorage_change'),
    re_path(r'^kitpartstorage/delete/(?P<id>[\d]+)/$', views.ajax_kitpartstorage_delete, name='ajax_kitpartstorage_delete'),
]

ims/inventory/api/urls.py
from django.urls import re_path
from inventory.api import views

app_name = 'invapi'
urlpatterns = [
    re_path(r'^part/$', views.PartList.as_view(), name='part_list'),
    re_path(r'^part/(?P<id>[\.\d]+)/$', views.PartDetail.as_view(), name='part_detail'),
    re_path(r'^part/(?P<id>[\.\d]+)/count/$', views.PartDetailCount.as_view(), name='part_count'),
    re_path(r'^part/(?P<id>[\.\d]+)/component/$', views.PartDetailComponent.as_view(), name='part_component'),
    re_path(r'^part/(?P<id>[\.\d]+)/assembly/$', views.PartDetailAssembly.as_view(), name='part_assembly'),
    re_path(r'^part/(?P<id>[\.\d]+)/storage/$', views.PartDetailStorage.as_view(), name='part_storage'),
    re_path(r'^part/(?P<parid>[\.\d]+)/storage/(?P<stoid>[\.\d]+)/add/(?P<inc>[\.\d]+)/$', views.PartAdd.as_view(), name='part_storage_add'),
    re_path(r'^part/(?P<parid>[\.\d]+)/storage/(?P<stoid>[\.\d]+)/subtract/(?P<inc>[\.\d]+)/$', views.PartSub.as_view(), name='part_storage_sub'),
    re_path(r'^part/(?P<id>[\.\d]+)/kit/$', views.PartDetailKit.as_view(), name='part_kit'),
    re_path(r'^part/(?P<partid>[\.\d]+)/kit/(?P<kitid>[\.\d]+)/add/(?P<inc>[\.\d]+)/$', views.PartDetailKitAdd.as_view(), name='part_kit_add'),
    re_path(r'^part/(?P<partid>[\.\d]+)/kit/(?P<kitid>[\.\d]+)/subtract/(?P<inc>[\.\d]+)/$', views.PartDetailKitSub.as_view(), name='part_kit_sub'),
    re_path(r'^assembly/$', views.AssemblyList.as_view(), name='assembly_list'),
    re_path(r'^assembly/(?P<id>[\.\d]+)/$', views.AssemblyDetail.as_view(), name='assembly_detail'),
    re_path(r'^assembly/(?P<id>[\.\d]+)/part/$', views.AssemblyDetailParts.as_view(), name='assembly_part'),
    re_path(r'^storage/$', views.StorageList.as_view(), name='storage_list'),
    re_path(r'^storage/(?P<id>[\.\d]+)/$', views.StorageDetail.as_view(), name='storage_detail'),
    re_path(r'^storage/(?P<id>[\.\d]+)/part/$', views.StorageDetailParts.as_view(), name='storage_part'),
    re_path(r'^storage/(?P<stoid>[\.\d]+)/part/(?P<parid>[\.\d]+)/add/(?P<inc>[\.\d]+)/$', views.PartAdd.as_view(), name='storage_part_add'),
    re_path(r'^storage/(?P<stoid>[\.\d]+)/part/(?P<parid>[\.\d]+)/subtract/(?P<inc>[\.\d]+)/$', views.PartSub.as_view(), name='storage_part_sub'),
    re_path(r'^altsku/$', views.AlternateSKUList.as_view(), name='alternatesku_list'),
    re_path(r'^altsku/(?P<id>[\.\d]+)/$', views.AlternateSKUDetail.as_view(), name='alternatesku_detail'),
    re_path(r'^partstorage/$', views.PartStorageList.as_view(), name='partstorage_list'),
    re_path(r'^partstorage/(?P<id>[\.\d]+)/$', views.PartStorageDetail.as_view(), name='partstorage_detail'),
    re_path(r'^partstorage/(?P<id>[\.\d]+)/add/(?P<count>[\.\d]+)/$', views.PartStorageAdd.as_view(), name='partstorage_add'),
    re_path(r'^partstorage/(?P<id>[\.\d]+)/subtract/(?P<count>[\.\d]+)/$', views.PartStorageSub.as_view(), name='partstorage_subtract'),
    re_path(r'^partaltsku/$', views.PartAlternateSKUList.as_view(), name='partaltsku_list'),
    re_path(r'^partaltsku/(?P<id>[\.\d]+)/$', views.PartAlternateSKUDetail.as_view(), name='partaltsku_detail'),
    re_path(r'^kit/$', views.KitList.as_view(), name='kit_list'),
    re_path(r'^kit/(?P<id>[\.\d]+)/$', views.KitDetail.as_view(), name='kit_detail'),
    re_path(r'^kit/(?P<id>[\.\d]+)/count/$', views.KitDetailCount.as_view(), name='kit_count'),
    re_path(r'^kit/(?P<id>[\.\d]+)/partstorage/$', views.KitDetailPartStorage.as_view(), name='kit_partstorage'),
    re_path(r'^kit/(?P<kitid>[\.\d]+)/add/(?P<inc>[\.\d]+)/$', views.KitAdd.as_view(), name='kit_add'),
    re_path(r'^kit/(?P<kitid>[\.\d]+)/subtract/(?P<inc>[\.\d]+)/$', views.KitSub.as_view(), name='kit_sub2'),
    re_path(r'^kitpartstorage/$', views.KitPartStorageList.as_view(), name='kitpartstorage_list'),
    re_path(r'^kitpartstorage/(?P<id>[\.\d]+)/$', views.KitPartStorageDetail.as_view(), name='kitpartstorage_detail'),
    re_path(r'^addpart/(?P<stoid>[\.\d]+)/(?P<parid>[\.\d]+)/(?P<inc>[\d]+)/$', views.PartAdd.as_view(), name='part_add'),
    re_path(r'^subpart/(?P<stoid>[\.\d]+)/(?P<parid>[\.\d]+)/(?P<inc>[\d]+)/$', views.PartSub.as_view(), name='part_sub'),
    re_path(r'^subkit/(?P<kitid>[\.\d]+)/(?P<inc>[\d]+)/$', views.KitSub.as_view(), name='kit_sub'),
]

ims/inventory/urls.py
from django.urls import re_path
from inventory import views

app_name='inventory'
urlpatterns = [
    re_path(r'^$', views.part_list, name='home'),
    re_path(r'^about/$', views.about_ims, name='about'),
    #re_path(r'^about/theme/$', views.ajax_theme, name='about'),
    re_path(r'^part/$', views.part_list, name='part_list'),
    re_path(r'^part/(?P<id>[\d]+)/$', views.part_detail, name='part_detail'),
    re_path(r'^container/$', views.storage_hierarchy_list, name='storage_hierarchy_list'),
    re_path(r'^container/(?P<id>[\d]+)/$', views.storage_hierarchy_detail, name='storage_hierarchy_detail'),
    re_path(r'^storage/$', views.storage_list, name='storage_list'),
    re_path(r'^storage/(?P<id>[\d]+)/$', views.storage_detail, name='storage_detail'),
    re_path(r'^partstorage/(?P<id>[\d]+)/add/(?P<inc>[\d]+)/$', views.ajax_partstorage_add, name='ajax_partstorage_add'),
    re_path(r'^partstorage/(?P<id>[\d]+)/sub/(?P<inc>[\d]+)/$', views.ajax_partstorage_sub, name='ajax_partstorage_sub'),
    re_path(r'^partstorage/(?P<id>[\d]+)/update/(?P<section>[\w]+)/$', views.ajax_partstorage_update, name='ajax_partstorage_update'),
    re_path(r'^altsku/$', views.altsku_list, name='altsku_list'),
    re_path(r'^assembly/$', views.assembly_list, name='assembly_list'),
    re_path(r'^assembly/(?P<id>[\d]+)/$', views.assembly_detail, name='assembly_detail'),
    re_path(r'^kit/$', views.kit_list, name='kit_list'),
    re_path(r'^kit/(?P<id>[\d]+)/$', views.kit_detail, name='kit_detail'),
    re_path(r'^kit/(?P<id>[\d]+)/add/(?P<inc>[\d]+)/$', views.ajax_kit_add, name='ajax_kit_add'),
    re_path(r'^kit/(?P<id>[\d]+)/sub/(?P<inc>[\d]+)/$', views.ajax_kit_subtract, name='ajax_kit_subtract'),
    re_path(r'^kit/(?P<id>[\d]+)/update/(?P<section>[\w]+)/$', views.ajax_kit_update, name='ajax_kit_update'),
    re_path(r'^search/$', views.search, name='search'),
]

ims/inventory/admin/forms.py
from django.forms import ModelForm

from inventory.models import Part, Assembly, Storage, AlternateSKU, PartStorage, PartAlternateSKU, Kit, KitPartStorage

class PartForm(ModelForm):
    class Meta:
        model = Part
        exclude = ['created', 'lastmodified']

class AssemblyForm(ModelForm):
    class Meta:
        model = Assembly
        exclude = ['created', 'lastmodified']

class StorageForm(ModelForm):
    class Meta:
        model = Storage
        exclude = ['created', 'lastmodified']
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['parent'].required = False

class AlternateSKUForm(ModelForm):
    class Meta:
        model = AlternateSKU
        exclude = ['created', 'lastmodified']

class PartStorageForm(ModelForm):
    class Meta:
        model = PartStorage
        exclude = ['created', 'lastmodified']

class PartAlternateSKUForm(ModelForm):
    class Meta:
        model = PartAlternateSKU
        exclude = ['created', 'lastmodified']

class KitForm(ModelForm):
    class Meta:
        model = Kit
        exclude = ['created', 'lastmodified']

class KitPartStorageForm(ModelForm):
    class Meta:
        model = KitPartStorage
        exclude = ['created', 'lastmodified']

ims/inventory/api/forms.py
from django import forms
from inventory.models import Part, Storage, AlternateSKU, PartAlternateSKU, PartStorage, Assembly, Kit, KitPartStorage

class PartForm(forms.ModelForm):
    class Meta:
        model = Part
        fields = ('name', 'description', 'sku', 'price', 'cost')

class StorageForm(forms.ModelForm):
    class Meta:
        model = Storage
        fields = ('name', 'description')

class AlternateSKUForm(forms.ModelForm):
    class Meta:
        model = AlternateSKU
        fields = ('manufacturer', 'sku')

class PartAlternateSKUForm(forms.ModelForm):
    class Meta:
        model = PartAlternateSKU
        fields = ('part', 'alt_sku')

class PartStorageForm(forms.ModelForm):
    class Meta:
        model = PartStorage
        fields = ('part', 'storage', 'count')

class AssemblyForm(forms.ModelForm):
    class Meta:
        model = Assembly
        fields = ('parent', 'part', 'count')

class KitForm(forms.ModelForm):
    class Meta:
        model = Kit
        fields = ('name', 'description', 'sku', 'price')

class KitPartStorage(forms.ModelForm):
    class Meta:
        model = KitPartStorage
        fields = ('kit', 'partstorage', 'count')

ims/inventory/forms.py
from django import forms

SEARCH_CHOICES =(
    ("3","Contains"),
    ("2","Exact"),
    ("1","Starts With"),
)

MODEL_CHOICES =(
    ("assembly","Assembly"),
    ("kit","Kit"),
    ("part","Part"),
    ("storage","Storage"),
    ("alternatesku","AlternateSKU"),
)

class ModelSearchForm(forms.Form):
    q = forms.CharField(max_length=100)
    m = forms.MultipleChoiceField(choices = MODEL_CHOICES, widget = forms.CheckboxSelectMultiple)
    t = forms.ChoiceField(choices = SEARCH_CHOICES, widget = forms.RadioSelect)

ims/templates/inventory/kit/detail.html
{% extends "inventory/base.html" %}
{% load get_setting %}
{% load static %}

{% block title %}{{ kit.name }}{% endblock %}

{% block content %}
<div class="w3-container" style="margin-top:65px;">
    <div class="w3-left">
        <h4><b>{{ kit.name }}</b> ({{ kit.sku }})</h4>
        <a class="w3-button ims-padding-small w3-hover-blue w3-margin-bottom" href="{{ previous }}" alt="View Previous Kit">Previous</a>
        <a class="w3-button ims-padding-small w3-hover-blue w3-margin-bottom" href="{{ next }}" alt="View Next Kit">Next</a>
    </div>
    <div class="w3-container">
        <div id="message" class="w3-col w3-padding w3-left"></div>
    </div>
    <div class="w3-container w3-margin-bottom">
        <div id="id_kitdetails" class="w3-padding w3-left w3-col l6 ims-card w3-card">
            <div class="w3-small">{{ kit.description }}</div>
            <div class="w3-left"><b>Price:</b> ${{ kit.price }}</div>
            <div class="w3-right"><b>Cost:</b> ${{ kit.get_cost }}</div>
            <div class="ims-middle-left"><b>Available:</b> {{ kit.get_available_count }}</div>
        </div>
        <div class="w3-padding w3-right w3-col l3">
            {% if perms.inventory.increment_kit %}
            <a href="javascript:void(0)" alt="Add 1 Kit to Inventory" class="w3-hover-green w3-button w3-round w3-border" onclick="addobj({{ kit.id }})">+ Add</a>
            {% endif %}{% if perms.inventory.decrement_kit %}
            <a href="javascript:void(0)" alt="Subtract 1 Kit from Inventory" class="w3-hover-red w3-button w3-round w3-border" onclick="subobj({{ kit.id }})">- Subtract</a>
            {% endif %}
        </div>
    </div>
    <div class="w3-container w3-margin-bottom">
        <div id="id_kitcomponents" class="w3-padding w3-left w3-col l6 ims-card w3-card">
            <div class="w3-left"><h5><b>Kit Components</b></h5></div>
            {% if perms.inventory.add_kitpartstorage %}
            <div class="w3-right">
                <a href="/inventory/admin/kitpartstorage/create/?kit={{ kit.id }}" alt="Add Component" class="w3-button w3-hover-green w3-round w3-border">+ New</a>
            </div>
            {% endif %}
            {% if kit.has_components %}
            {% for kps in kit.get_components %}
            <div class="w3-padding w3-left w3-col ims-card w3-card">
                <div class="w3-left ims-padding-small"><a href="{{ kps.partstorage.storage.get_absolute_url }}" alt="View Storage {{ kps.partstorage.storage.name }}"><b>{{ kps.partstorage.storage.name }}</b></a> - <a href="{{ kps.partstorage.part.get_absolute_url }}" alt="View Part {{ kps.partstorage.part.name }}"><b>{{ kps.partstorage.part.name }}</b></a></div>
                <div class="w3-right ims-padding-small">x{{ kps.count }}</div>
            </div>
            {% endfor %}
            {% endif %}
        </div>
    </div>
</div>
<script src="{% static "common/js/jquery.min.js" %}"></script>
<script>{% if perms.inventory.decrement_kit %}
    function subobj(id) {
        $.ajax({
            url: '/inventory/kit/' + id + '/sub/1/',
            type: 'get',
            success: function(data) {
                $("#message").html(data);
                $.ajax({
                    url: '/inventory/kit/' + id + '/update/kitcomponents/',
                    type: 'get',
                    success: function(data) {
                        $("#id_kitcomponents").html(data);
                    }
                });
                $.ajax({
                    url: '/inventory/kit/' + id + '/update/kitdetails/',
                    type: 'get',
                    success: function(data) {
                        $("#id_kitdetails").html(data);
                    }
                });
            }
        });
    }{% endif %}{% if perms.inventory.increment_kit %}
    function addobj(id) {
        $.ajax({
            url: '/inventory/kit/' + id + '/add/1/',
            type: 'get',
            success: function(data) {
                $("#message").html(data);
                $.ajax({
                    url: '/inventory/kit/' + id + '/update/kitcomponents/',
                    type: 'get',
                    success: function(data) {
                        $("#id_kitcomponents").html(data);
                    }
                });
                $.ajax({
                    url: '/inventory/kit/' + id + '/update/kitdetails/',
                    type: 'get',
                    success: function(data) {
                        $("#id_kitdetails").html(data);
                    }
                });
            }
        });
    }{% endif %}
</script>
{% endblock %}

ims/templates/inventory/kit/list.html
{% extends "inventory/base.html" %}
{% load get_setting %}

{% block title %}Kits List{% endblock %}

{% block content %}
<div class="w3-container" style="margin-top:65px;">
    <div class="w3-left w3-margin-top">
        <h4><b>Kits List</b></h4>
    </div>
    {% if perms.inventory.add_kit %}
    <div class="w3-right">
        <a href="/inventory/admin/kit/create/" alt="Add Kit" class="w3-button w3-hover-green w3-round w3-border">+ New</a>
    </div>
    {% endif %}
    <div class="w3-container">
        {% for kit in kits %}
        {% cycle "add" "not" as parentdiv silent %}
        {% if parentdiv == "add" %}<div class="w3-col">{% endif %}
        <div class="w3-col l12 xl6 w3-padding ims-card w3-card">
            <a href="{{ kit.get_absolute_url }}" class="w3-medium" alt="View Kit {{ kit.name }}"><b>{{ kit.name }}</b> ({{ kit.sku }})</a>
            <a href="javascript:void(0)" onclick="ims_expand(this)" class="w3-button w3-right" alt="Expand information for {{ kit.name }}">+</a>
            <div class="w3-col w3-padding ims-hidden ims-card w3-card">
                <div class="w3-left w3-col w3-small">{{ kit.description }}</div>
                <div class="w3-left"><u>Price:</u> ${{ kit.price }}</div>
            </div>
        {% if parentdiv == "not" %}</div>
        </div>{% else %}</div>{% endif %}
        {% endfor %}
    </div>
{% include "inventory/pagination.html" with page=kits %}
</div>
<script>
    function ims_expand(elem) {
        var parent = elem.parentNode;
        var child_div = parent.getElementsByTagName("div")[0];
        if (elem.text === "+") {
            elem.text = "-";
            child_div.classList.remove("ims-hidden");
        } else {
            elem.text = "+";
            child_div.classList.add("ims-hidden");
        }
    }
</script>
{% endblock %}
{% block sidebar %}
<div id="search" class="ims-search-bar w3-padding w3-card" style="top:43px;">
    <form method="get" style="margin:0;">
        <input class="w3-round ims-form-field" type="text" placeholder="search for kits" name="q"{% if query %} value="{{ query }}"{% endif %}/>
        <button class="w3-button w3-round" type="submit">Search</button>
    </form>
</div>
<script>
    var prev_scroll_pos = window.pageYOffset;
    window.onscroll = function() {
        var current_scroll_pos = window.pageYOffset;
        var elem = document.getElementById("search");
        if (prev_scroll_pos > current_scroll_pos) {
            elem.style.top = "43px";
        } else {
            elem.style.top = "-15px";
        }
        prev_scroll_pos = current_scroll_pos;
    }
</script>
{% endblock %}