ims/accounts/admin/urls.py
from django.urls import path,re_path
from accounts.admin import views

app_name='accounts.admin'
urlpatterns = [
    path('', views.home, name='home'),
    path('invite/', views.admin_invite_view, name='admin_invite_view'),
    path('invite/create/', views.admin_invite_create, name='admin_invite_create'),
    re_path(r'^invite/change/(?P<id>[\d]+)/$', views.admin_invite_change, name='admin_invite_change'),
    re_path(r'^invite/delete/(?P<id>[\d]+)/$', views.ajax_invite_delete, name='ajax_invite_delete'),
    path('token/', views.admin_token_view, name='admin_token_view'),
    path('token/create/', views.admin_token_create, name='admin_token_create'),
    re_path(r'^token/delete/(?P<id>[\d]+)/$', views.ajax_token_delete, name='ajax_token_delete'),
    path('group/', views.admin_group_view, name='admin_group_view'),
    path('group/create/', views.admin_group_create, name='admin_group_create'),
    re_path(r'^group/change/(?P<id>[\d]+)/$', views.admin_group_change, name='admin_group_change'),
    re_path(r'^group/delete/(?P<id>[\d]+)/$', views.ajax_group_delete, name='ajax_group_delete'),
    path('user/', views.admin_user_view, name='admin_user_view'),
    path('user/create/', views.admin_user_create, name='admin_user_create'),
    re_path(r'^user/change/(?P<id>[\d]+)/password/$', views.admin_user_change_password, name='admin_user_change_password'),
    re_path(r'^user/change/(?P<id>[\d]+)/$', views.admin_user_change, name='admin_user_change'),
    re_path(r'^user/delete/(?P<id>[\d]+)/$', views.ajax_user_delete, name='ajax_user_delete'),
    re_path(r'^user/unlock/(?P<id>[\d]+)/$', views.ajax_user_unlock, name='ajax_user_unlock'),
]

ims/accounts/api/urls.py
from django.urls import path,re_path
from accounts.api import views

app_name='accounts.api'
urlpatterns = [
    path('token-auth/', views.obtain_auth_token, name='obtain_auth_token'),
    path('group/', views.GroupList.as_view(), name='group_list'),
    re_path(r'^group/(?P<gid>[\.\d]+)/$', views.GroupDetail.as_view(), name='group_detail'),
    re_path(r'^group/(?P<gid>[\.\d]+)/users/$', views.GroupUserDetail.as_view(), name='group_userdetail'),
    re_path(r'^group/(?P<gid>[\.\d]+)/users/add/(?P<uid>[\.\d]+)/$', views.GroupUserAdd.as_view(), name='group_useradd'),
    re_path(r'^group/(?P<gid>[\.\d]+)/users/remove/(?P<uid>[\.\d]+)/$', views.GroupUserRemove.as_view(), name='group_userremove'),
    re_path(r'^group/(?P<gid>[\.\d]+)/permissions/$', views.GroupPermissionDetail.as_view(), name='group_permissiondetail'),
    re_path(r'^group/(?P<gid>[\.\d]+)/permissions/add/(?P<pid>[\.\d]+)/$', views.GroupPermissionAdd.as_view(), name='group_permissionadd'),
    re_path(r'^group/(?P<gid>[\.\d]+)/permissions/remove/(?P<pid>[\.\d]+)/$', views.GroupPermissionRemove.as_view(), name='group_permissionremove'),
    path('invite/', views.InviteList.as_view(), name='invite_list'),
    re_path(r'^invite/(?P<iid>[\.\d]+)/$', views.InviteDetail.as_view(), name='invite_detail'),
    path('permission/', views.PermissionList.as_view(), name='permission_list'),
    re_path(r'^permission/(?P<pid>[\.\d]+)/$', views.PermissionDetail.as_view(), name='permission_detail'),
    re_path(r'^permission/(?P<pid>[\.\d]+)/groups/$', views.PermissionGroupDetail.as_view(), name='permission_groupdetail'),
    re_path(r'^permission/(?P<pid>[\.\d]+)/groups/add/(?P<gid>[\.\d]+)/$', views.PermissionGroupAdd.as_view(), name='permission_groupadd'),
    re_path(r'^permission/(?P<pid>[\.\d]+)/groups/remove/(?P<gid>[\.\d]+)/$', views.PermissionGroupRemove.as_view(), name='permission_groupremove'),
    re_path(r'^permission/(?P<pid>[\.\d]+)/users/$', views.PermissionUserDetail.as_view(), name='permission_userdetail'),
    re_path(r'^permission/(?P<pid>[\.\d]+)/users/add/(?P<uid>[\.\d]+)/$', views.PermissionUserAdd.as_view(), name='permission_useradd'),
    re_path(r'^permission/(?P<pid>[\.\d]+)/users/remove/(?P<uid>[\.\d]+)/$', views.PermissionUserRemove.as_view(), name='permission_userremove'),
    path('token/', views.TokenList.as_view(), name='token_list'),
    re_path(r'^token/(?P<tid>[\.\d]+)/$', views.TokenDetail.as_view(), name='token_detail'),
    path('user/', views.UserList.as_view(), name='user_list'),
    re_path(r'^user/(?P<uid>[\.\d]+)/$', views.UserDetail.as_view(), name='user_detail'),
    re_path(r'^user/(?P<uid>[\.\d]+)/disable/$', views.UserDisable.as_view(), name='user_disable'),
    re_path(r'^user/(?P<uid>[\.\d]+)/enable/$', views.UserEnable.as_view(), name='user_enable'),
    re_path(r'^user/(?P<uid>[\.\d]+)/groups/$', views.UserGroupDetail.as_view(), name='user_groupdetail'),
    re_path(r'^user/(?P<uid>[\.\d]+)/groups/add/(?P<gid>[\.\d]+)/$', views.UserGroupAdd.as_view(), name='user_groupadd'),
    re_path(r'^user/(?P<uid>[\.\d]+)/groups/remove/(?P<gid>[\.\d]+)/$', views.UserGroupRemove.as_view(), name='user_groupremove'),
    re_path(r'^user/(?P<uid>[\.\d]+)/lock/$', views.UserLock.as_view(), name='user_lock'),
    re_path(r'^user/(?P<uid>[\.\d]+)/permissions/$', views.UserPermissionDetail.as_view(), name='user_permissiondetail'),
    re_path(r'^user/(?P<uid>[\.\d]+)/permissions/add/(?P<pid>[\.\d]+)/$', views.UserPermissionAdd.as_view(), name='user_permissionadd'),
    re_path(r'^user/(?P<uid>[\.\d]+)/permissions/remove/(?P<pid>[\.\d]+)/$', views.UserPermissionRemove.as_view(), name='user_permissionremove'),
    re_path(r'^user/(?P<uid>[\.\d]+)/unlock/$', views.UserUnlock.as_view(), name='user_unlock'),
]

ims/accounts/urls.py
from django.conf import settings
from django.urls import path,re_path
from accounts import views

app_name='accounts'
urlpatterns = [
    path('invite/<token>/', views.invite_code, name='invite_code'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.user_profile, name='user_profile'),
    path('profile/edit/', views.user_edit, name='user_edit'),
    path('profile/token/', views.ajax_view_tokens, name='ajax_view_tokens'),
    path('profile/token/create/', views.ajax_create_token, name='ajax_create_token'),
    re_path(r'^profile/token/(?P<id>[\d]+)/$', views.view_token, name='view_token'),
    re_path(r'^profile/token/(?P<id>[\d]+)/delete/$', views.ajax_delete_token, name='ajax_delete_token'),
    path('signup/', views.sign_up, name='sign_up'),
]

ims/ims/urls.py
"""
Definition of urls for ims.
"""

from django.contrib import admin
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView, PasswordChangeView, PasswordChangeDoneView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static
from mfa.views import LoginView
from . import views
import re

urlpatterns = [
    path('mfa/', include('mfa.urls', namespace='mfa')),
    path('accounts/admin/', include('accounts.admin.urls')),
    path('accounts/password_change/', PasswordChangeView.as_view(), name='password_change'),
    path('accounts/password_change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('accounts/password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('accounts/', include('accounts.urls')),
    path('admin/login/', LoginView.as_view()),
    path('admin/', admin.site.urls),
    path('inventory/admin/', include('inventory.admin.urls')),
    path('inventory/', include('inventory.urls')),
    path('logs/', include('log.urls')),
    path('api/v1/accounts/', include('accounts.api.urls')),
    path('api/v1/inventory/', include('inventory.api.urls')),
    path('api/v1/log/', include('log.api.urls')),
    path('api-auth/', include('rest_framework.urls')),
    re_path(r'^$', views.root_view, name='redirect'),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

regex = re.compile(r'ims.addons.*')
addons = [i for i in settings.INSTALLED_APPS if regex.match(i)]

for module in addons:
    name = module.replace('ims.addons.','')
    for line in settings.INSTALLED_ADDONS:
        if line['name'].lower() == name:
            if line['enabled']:
                if 'api_url' in line:
                    urlpatterns.append(path(line['api_url'], include('{}.api.urls'.format(module))))
                if 'admin_url' in line:
                    urlpatterns.append(path(line['admin_url'], include('{}.admin.urls'.format(module))))
                if 'url' in line:
                    urlpatterns.append(path(line['url'], include('{}.urls'.format(module))))
                if 'other_urls' in line:
                    array = line['other_urls'].split('|')
                    if len(array)%2 == 0:
                        i=0
                        while i < len(array):
                            urlpatterns.append(path(array[i].split(':')[1], include(array[i+1].split(':')[1])))
                            i+=2

ims/accounts/models.py
from binascii import hexlify
from django.conf import settings
from django.contrib.auth.models import Group, User
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from os import urandom
from secrets import token_urlsafe
import logging

logger = logging.getLogger(__name__)


class Invite(models.Model):
    email = models.EmailField()
    code = models.CharField(max_length=86)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    expires = models.DateTimeField(default=None,editable=True,blank=True,null=True)
    created = models.DateTimeField(auto_now_add=True,editable=False)
    lastmodified = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['email']

    def save(self, *args, **kwargs):
        if self.id != None:
            logger.info('Saving changes made to Invite id {}'.format(self.id))
        else:
            self.code = token_urlsafe(48)
            logger.info('Creating new Invite "{}"'.format(self.email))
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        logger.info('Deleting Invite id {}'.format(self.id))
        super().delete(*args, **kwargs)

    def __str__(self):
        return self.email

    def get_absolute_url(self):
        logger.debug('Generating absolute URL for Invite id {}'.format(self.id))
        return reverse('accounts:invite_code', args=[self.code])

class Token(models.Model):
    key = models.CharField(_("Key"), max_length=40)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='ims_authtoken', on_delete=models.CASCADE, verbose_name=_("User"))
    created = models.DateTimeField(_("Created"), auto_now_add=True)
    expires = models.DateTimeField(_("Expires"), default=None,editable=True,blank=True,null=True)

    class Meta:
        abstract = 'rest_framework.authtoken' not in settings.INSTALLED_APPS
        ordering = ['expires']
        verbose_name = _("Token")
        verbose_name_plural = _("Tokens")

    def save(self, *args, **kwargs):
        if not self.key:
            self.key = self.generate_key()
        return super().save(*args, **kwargs)
    
    @classmethod
    def generate_key(cls):
        return hexlify(urandom(20)).decode()
    
    def __str__(self):
        return self.key
    
class UserMetadata(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,primary_key=True,related_name='metadata')
    bad_password_attempts = models.PositiveSmallIntegerField(default=0)
    is_locked_out = models.BooleanField(default=False)
    last_set_password_datetime = models.DateTimeField(auto_now_add=True, editable=False)
    last_lockout_datetime = models.DateTimeField(editable=False, blank=True, null=True,)
    last_bad_password_datetime = models.DateTimeField(editable=False, blank=True, null=True)
    must_change_password = models.BooleanField(default=False)

ims/templates/accounts/admin/create.html
{% extends "inventory/base.html" %}
{% load get_setting %}
{% load custom_tags %}
{% load static %}
{% block title %}New {{ name }}{% endblock %}
{% block content %}
<link href="{% static "common/css/MultiSelect.css" %}" rel="stylesheet" type="text/css">
<div class="w3-container w3-padding w3-light-gray" style="margin-top:20px;">
    <a href="/accounts/admin/" alt="Accounts Admin">Accounts Admin</a>
    »
    <a href="/accounts/admin/{{ name|lower }}/" alt="Accounts Admin {{ name }}">{{ name }}</a>
    » Add {{ name }}
</div>
<div class="w3-container">
    <div class="w3-left w3-margin-top">
        <h4><b>New {{ name }}</b></h4>
    </div>
    <div class="w3-container">
        <div class="w3-col w3-padding w3-left">{{ message }}</div>
    </div>
    <div class="w3-container">
        <form class="w3-col l12 xl6 w3-padding w3-bar-block ims-card w3-card" action="." method="post">
            {% csrf_token %}
            {{ form.non_field_errors }}
            {% for field in form %}
            <div class="w3-bar-item">
                {{ field.errors }}
                {{ field | add_classes_and_auto_format:"w3-left ims-select-options ims-form-field" }}
            </div>
            {% endfor %}
            <div class="w3-bar-item">
                <input type="submit" class="w3-button w3-dark-grey ims-form-field" value="Create">
            </div>
            <div class="w3-bar-item">
                <a href="/accounts/admin/" class="w3-button w3-light-grey ims-form-field">Cancel</a>
            </div>
        </form>
    </div>
</div>
<script src="{% static "common/js/MultiSelect.js" %}"></script>
{% endblock %}

ims/templates/accounts/admin/home.html
{% extends "inventory/base.html" %}
{% load get_setting %}
{% load custom_tags %}
{% block title %}Accounts Admin{% endblock %}
{% block content %}
<div class="w3-container" style="margin-top:65px;">
    <div class="w3-left w3-margin-top">
        <h4><b>Accounts Admin</b></h4>
    </div>
    <div class="w3-container">
        <div class="w3-col l12 xl6 w3-padding w3-bar-block ims-card w3-card">
            {% if perms.auth.view_group %}
            <div class="w3-bar-item">
                <a class="w3-button ims-form-field" href="/accounts/admin/group/">Groups</a>
            </div>
            {% endif %}
            {% if perms.accounts.view_invite %}
            <div class="w3-bar-item">
                <a class="w3-button ims-form-field" href="/accounts/admin/invite/">Invites</a>
            </div>
            {% endif %}
            {% if perms.accounts.view_token %}
            <div class="w3-bar-item">
                <a class="w3-button ims-form-field" href="/accounts/admin/token/">Tokens</a>
            </div>
            {% endif %}
            {% if perms.auth.view_user %}
            <div class="w3-bar-item">
                <a class="w3-button ims-form-field" href="/accounts/admin/user/">Users</a>
            </div>
            {% endif %}
    </div>
    </div>
</div>
{% endblock %}

ims/templates/accounts/admin/update.html
{% extends "inventory/base.html" %}
{% load get_setting %}
{% load custom_tags %}
{% load static %}
{% block title %}Update {{ name }}{% endblock %}
{% block content %}
<link href="{% static "common/css/MultiSelect.css" %}" rel="stylesheet" type="text/css">
<div class="w3-container w3-padding w3-light-gray" style="margin-top:20px;">
    <a href="/accounts/admin/" alt="Accounts Admin">Accounts Admin</a>
    »
    <a href="/accounts/admin/{{ objtype|lower }}/" alt="Accounts Admin {{ objtype }}">{{ objtype }}</a>
    » {{ name }}
</div>
<div class="w3-container">
    <div class="w3-left w3-margin-top">
        <h4><b>Update {{ name }}</b></h4>
    </div>
    <div class="w3-container">
        <div class="w3-col w3-padding w3-left">{{ message }}</div>
    </div>
    <div class="w3-container">
        <form class="w3-col l12 xl6 w3-padding w3-bar-block ims-card w3-card" action="." method="post">
            {% csrf_token %}
            {{ form.non_field_errors }}
            {% for field in form %}
            <div class="w3-bar-item">
                {{ field.errors }}
                {{ field | add_classes_and_auto_format:"w3-left ims-select-options ims-form-field" }}
            </div>
            {% endfor %}
            <div class="w3-bar-item">
                <input type="submit" class="w3-button w3-dark-grey ims-form-field" value="Update">
            </div>
            <div class="w3-bar-item">
                <a href="/accounts/admin/" class="w3-button w3-light-grey ims-form-field">Cancel</a>
            </div>
        </form>
    </div>
</div>
<script src="{% static "common/js/MultiSelect.js" %}"></script>
{% endblock %}

ims/templates/accounts/admin/user_create.html
{% extends "inventory/base.html" %}
{% load get_setting %}
{% load custom_tags %}
{% load static %}
{% block title %}New {{ name }}{% endblock %}
{% block content %}
<link href="{% static "common/css/MultiSelect.css" %}" rel="stylesheet" type="text/css">
<div class="w3-container w3-padding w3-light-gray" style="margin-top:20px;">
    <a href="/accounts/admin/" alt="Accounts Admin">Accounts Admin</a>
    »
    <a href="/accounts/admin/{{ name|lower }}/" alt="Accounts Admin {{ name }}">{{ name }}</a>
    » Add {{ name }}
</div>
<div class="w3-container">
    <div class="w3-left w3-margin-top">
        <h4><b>New {{ name }}</b></h4>
    </div>
    <div class="w3-container">
        <div class="w3-col w3-padding w3-left">{{ message }}</div>
    </div>
    <div class="w3-container">
        <form class="w3-col l12 xl6 w3-padding w3-bar-block ims-card w3-card" action="." method="post">
            {% csrf_token %}
            {% if user_form %}
            {{ user_form.non_field_errors }}
            {% for field in user_form %}
            {% if field.field.widget.input_type == 'checkbox' %}
            <div class="w3-bar-item ims-chkb-wrap">
                {{ field.errors }}
                {{ field | add_classes:"ims-tgl ims-tgl-skewed" }}
		    <label class="w3-left ims-form-field ims-tgl-btn" data-tg-off="Disabled" data-tg-on="Enabled" for="{{ field.id_for_label }}" />
            </div>
            {% else %}
            <div class="w3-bar-item">
                {{ field.errors }}{{ field.label }}
                {{ field | add_classes:"w3-left ims-select-options ims-form-field" }}
            </div>
            {% endif %}
            {% endfor %}
            {% endif %}
            {{ group_form.non_field_errors }}
            {% for field in group_form %}
            <div class="w3-bar-item">
                {{ field.errors }}{{ field.label }}
                {{ field | add_classes:"w3-left ims-select-options ims-form-field" }}
            </div>
            {% endfor %}
            {{ permission_form.non_field_errors }}
            {% for field in permission_form %}
            <div class="w3-bar-item">
                {{ field.errors }}{{ field.label }}
                {{ field | add_classes:"w3-left ims-select-options ims-form-field" }}
            </div>
            {% endfor %}
            <div class="w3-bar-item">
                <input type="submit" class="w3-button w3-dark-grey ims-form-field" value="Create">
            </div>
            <div class="w3-bar-item">
                <a href="/accounts/admin/" class="w3-button w3-light-grey ims-form-field">Cancel</a>
            </div>
        </form>
    </div>
</div>
<script src="{% static "common/js/MultiSelect.js" %}"></script>
{% endblock %}

ims/templates/accounts/admin/user_update.html
{% extends "inventory/base.html" %}
{% load get_setting %}
{% load custom_tags %}
{% load static %}
{% block title %}Update {{ name }}{% endblock %}
{% block content %}
<link href="{% static "common/css/MultiSelect.css" %}" rel="stylesheet" type="text/css">
<div class="w3-container w3-padding w3-light-gray" style="margin-top:20px;">
    <a href="/accounts/admin/" alt="Accounts Admin">Accounts Admin</a>
    »
    <a href="/accounts/admin/{{ objtype|lower }}/" alt="Accounts Admin {{ objtype }}">{{ objtype }}</a>
    » {{ name }}
</div>
<div class="w3-container">
    <div class="w3-left w3-margin-top">
        <h4><b>Update {{ name }}</b></h4>
    </div>
    <div class="w3-container">
        <div class="w3-col w3-padding w3-left">{{ message }}</div>
    </div>
    <div class="w3-container">
        <form class="w3-col l12 xl6 w3-padding w3-bar-block ims-card w3-card" action="." method="post">
            {% csrf_token %}
            {{ user_form.non_field_errors }}
            {% for field in user_form %}
            {% if field.field.widget.input_type == 'checkbox' %}
            <div class="w3-bar-item ims-chkb-wrap">
                {{ field.errors }}
                {{ field | add_classes:"ims-tgl ims-tgl-skewed" }}
		    <label class="w3-left ims-form-field ims-tgl-btn" data-tg-off="Disabled" data-tg-on="Enabled" for="{{ field.id_for_label }}" />
            </div>
            {% else %}
            <div class="w3-bar-item">
                {{ field.errors }}{{ field.label }}
                {{ field | add_classes:"w3-left ims-select-options ims-form-field" }}
            </div>
            {% endif %}
            {% endfor %}
            {{ group_form.non_field_errors }}
            {% for field in group_form %}
            <div class="w3-bar-item">
                {{ field.errors }}{{ field.label }}
                {{ field | add_classes:"w3-left ims-select-options ims-form-field" }}
            </div>
            {% endfor %}
            {{ permission_form.non_field_errors }}
            {% for field in permission_form %}
            <div class="w3-bar-item">
                {{ field.errors }}{{ field.label }}
                {% if field.name == 'perms' %}
                {{ field | add_classes:"w3-left ims-select-options ims-form-field ims-select-multiple" }}
                {% else %}
                {{ field | add_classes:"w3-left ims-select-options ims-form-field" }}
                {% endif %}
            </div>
            {% endfor %}
            {{ metadata_form.non_field_errors }}
            {% for field in metadata_form %}
            {% if field.field.widget.input_type == 'checkbox' %}
            <div class="w3-bar-item ims-chkb-wrap">
                {{ field.errors }}
                {{ field | add_classes:"ims-tgl ims-tgl-skewed" }}
		    <label class="w3-left ims-form-field ims-tgl-btn" data-tg-off="No Password Reset" data-tg-on="Force Password Reset" for="{{ field.id_for_label }}" />
            </div>
            {% else %}
            <div class="w3-bar-item">
                {{ field.errors }}{{ field.label }}
                {{ field | add_classes:"w3-left ims-select-options ims-form-field" }}
            </div>
            {% endif %}
            {% endfor %}
            <div class="w3-bar-item">
                <input type="submit" class="w3-button w3-dark-grey ims-form-field" value="Update">
            </div>
            <div class="w3-bar-item">
                <a href="/accounts/admin/" class="w3-button w3-light-grey ims-form-field">Cancel</a>
            </div>
        </form>
    </div>
</div>
<script src="{% static "common/js/MultiSelect.js" %}"></script>
{% endblock %}